name: Kafka Microservices CI

on:
  push:
    branches:
      - main

jobs:
  build-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Order Service
        run: |
          cd orderservice
          mvn clean verify -DskipTests

      - name: Build Payment Service
        run: |
          cd paymentservice
          mvn clean verify -DskipTests

      - name: Build Notification Service
        run: |
          cd notificationservice
          mvn clean verify -DskipTests